---

- name: install mailcatcher
  gem: name=mailcatcher state=latest executable=/usr/local/bin/gem user_install=no

- name: set mailcatcher control script
  template: src=mailcatcher.sh dest=/etc/init.d/mailcatcher mode=755

- name: add mailcatcher service
  command: chkconfig --add mailcatcher

- name: start mailcatcher
  command: service mailcatcher start
