---

- name: install mysql packages
  yum: pkg={{ item }} state=installed
  with_items:
    - mysql-server
    - mysql
    - MySQL-python

- name: ensure mysqld is running and starts on boot
  service: name=mysqld state=started enabled=true

- name: update mysql root password for all root accounts
  shell: >
      mysql -u root -NBe
      'SET PASSWORD FOR "root"@"localhost" = PASSWORD("{{ mysql_root_password }}");'

- name: create mysql configuration file
  template: src=my.cnf dest=/root/.my.cnf owner=root mode=0600
  notify:
    - restart mysqld

- name: create mysql database
  mysql_db: name={{ mysql_db_name }} state=present

- name: remove anonymous mysql users
  mysql_user: name="" host={{ item }} state=absent
  with_items:
    - localhost
    - 127.0.0.1
    - ::1

- name: remove mysql test database
  mysql_db: name=test state=absent
