---

- name: install PHP packages
  yum: pkg={{ item }} state=installed
  with_items:
    - php56
    - php56-php-pecl-gearman
    - php56-php-pecl-xdebug
    - php56-php-intl
    - php56-php-pecl-apcu
    - php56-php-pdo
    - php56-php-mysqlnd
    - php56-php-mbstring

- template: src=php.ini dest=/opt/remi/php56/root/etc/php.d/99-overwrites.ini
  notify: restart httpd

- file: src=/usr/bin/php56 dest=/usr/bin/php state=link
