---

- name: Install an awesome project
  hosts: all
  environment:
    PATH:$PATH:/usr/local/bin
  roles:
    - geerlingguy.repo-remi
    - common
    - httpd
    - php
    - mysql
    - supervisord
    - gearman
    - mailcatcher
